Update required packages
Add ruby-dev & build-essential to required packages

Fix for:

```
Error: Could not update: Execution of '/usr/bin/gem install -v 0.6.9.4 --no-rdoc --no-ri charlock_holmes' returned 1: Building native extensions.  This could take a while...
ERROR:  Error installing charlock_holmes:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:1:in `<main>'
```