manifest/params.pp: Add ruby-devel dependency on EL platform
Currently, when install charlock_holmes gem, this is what occurs :

```
/usr/bin/gem install -v 0.6.9.4 --no-rdoc --no-ri charlock_holmes
Building native extensions.  This could take a while...
ERROR:  Error installing charlock_holmes:
        ERROR: Failed to build gem native extension.
/usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/ruby.h
```

The package ruby-devel is missing on EL platforms.